//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickApp.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickApp.Core.Localization.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol ekle.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı ekle.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolü silmek istediğinizden emin misiniz ?.
        /// </summary>
        public static string DoYouWantToRemoveRole {
            get {
                return ResourceManager.GetString("DoYouWantToRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıyı silmek istediğinizden emin misiniz ?.
        /// </summary>
        public static string DoYouWantToRemoveUser {
            get {
                return ResourceManager.GetString("DoYouWantToRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Numarası.
        /// </summary>
        public static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanlar.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana sayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarısız.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzinler.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa yönetimi.
        /// </summary>
        public static string QuickApp_Pages {
            get {
                return ResourceManager.GetString("QuickApp.Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string QuickApp_Pages_Home {
            get {
                return ResourceManager.GetString("QuickApp.Pages.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol yönetimi.
        /// </summary>
        public static string QuickApp_Pages_Roles {
            get {
                return ResourceManager.GetString("QuickApp.Pages.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol oluşturabilir.
        /// </summary>
        public static string QuickApp_Pages_Roles_CanCreateRoles {
            get {
                return ResourceManager.GetString("QuickApp.Pages.Roles.CanCreateRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı yönetimi.
        /// </summary>
        public static string QuickApp_Pages_Users {
            get {
                return ResourceManager.GetString("QuickApp.Pages.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı oluşturabilir.
        /// </summary>
        public static string QuickApp_Pages_Users_CanCreateUsers {
            get {
                return ResourceManager.GetString("QuickApp.Pages.Users.CanCreateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni hatırla.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol silme işlemi.
        /// </summary>
        public static string RemoveRole {
            get {
                return ResourceManager.GetString("RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı silme işlemi.
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol başarıyla silindi.
        /// </summary>
        public static string RoleDeletedSuccessfuly {
            get {
                return ResourceManager.GetString("RoleDeletedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role adı.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol yönetimi.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol başarıyla kaydedildi.
        /// </summary>
        public static string RoleSavedSuccessfuly {
            get {
                return ResourceManager.GetString("RoleSavedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlemi yapmaya yetkiniz yoktur..
        /// </summary>
        public static string UnAuthorizedRequest {
            get {
                return ResourceManager.GetString("UnAuthorizedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu tarafında beklenmeyen bir hata oluştu..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla silindi.
        /// </summary>
        public static string UserDeletedSuccessfuly {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre yanlış.
        /// </summary>
        public static string UsernameOrPasswordWrong {
            get {
                return ResourceManager.GetString("UsernameOrPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı yönetimi.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla kaydedildi.
        /// </summary>
        public static string UserSavedSuccessfuly {
            get {
                return ResourceManager.GetString("UserSavedSuccessfuly", resourceCulture);
            }
        }
    }
}
